# Generated by Django 5.0.2 on 2025-03-03 19:30

import django.db.models.deletion
import lms.apps.attachments.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('extension', models.CharField(blank=True, max_length=100, verbose_name='Extension')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt')),
                ('url', models.URLField(blank=True, max_length=255, verbose_name='URL')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='Size')),
                ('file_type', models.CharField(default='file', max_length=20, verbose_name='File Type')),
                ('parent', models.BigIntegerField(blank=True, null=True, verbose_name='Parent')),
                ('file', models.FileField(blank=True, null=True, upload_to=lms.apps.attachments.utils.get_default_upload_file_name, verbose_name='File')),
                ('storage_engine', models.CharField(default='local', max_length=20, verbose_name='Storage Engine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment_type', models.CharField(max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ('-id',),
                'abstract': False,
            },
        ),
    ]
