# Generated by Django 5.0.2 on 2025-05-27 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lessons', '0060_lesson_author_lesson_created_at_lesson_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonbatch',
            name='parent_lesson_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_batches', to='api_lessons.lessonbatch', verbose_name='Родительская коллекция уроков'),
        ),
    ]
