//app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { NavigationProgress } from "@/components/navigation-progress";
import { AuthContextProvider } from "@/context/auth-context";
import { Provider as NiceModalContextProvider } from "@/context/nice-modal-context";
import { TanstackContextProvider } from "@/context/tanstack-context";
import { Toaster } from "sonner";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <AuthContextProvider>
          <TanstackContextProvider>
            <NiceModalContextProvider>
              <NavigationProgress />
              <Toaster duration={50000} />
              {children}
            </NiceModalContextProvider>
          </TanstackContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
