def getUid(comonentId):
    """
    This function takes a component ID and returns a unique identifier (UID) for it.
    The UID is generated by replacing the first character of the component ID with 'u'.
    """
    return 'elem' + str(comonentId)